openapi: 3.0.0
info:
  title: Microservice Template API
  description: A simple API for the microservice template
  version: 1.0.0
servers:
  - url: /api/v1
    description: API version 1
tags:
  - name: Examples
    description: Example operations
paths:
  /examples:
    get:
      summary: Get all examples
      tags:
        - Examples
      responses:
        '200':
          description: A list of examples
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  results:
                    type: integer
                    example: 2
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Example'
    post:
      summary: Create a new example
      tags:
        - Examples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleInput'
      responses:
        '201':
          description: Example created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/Example'
  /examples/{id}:
    get:
      summary: Get an example by ID
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Example found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/Example'
        '404':
          description: Example not found
    put:
      summary: Update an example
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleInput'
      responses:
        '200':
          description: Example updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    $ref: '#/components/schemas/Example'
        '404':
          description: Example not found
    delete:
      summary: Delete an example
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Example deleted
        '404':
          description: Example not found
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        name:
          type: string
          example: Example name
        description:
          type: string
          example: Example description
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ExampleInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Example name
        description:
          type: string
          example: Example description
